name: Typst
permissions:
  contents: write
  actions: write
  pull-requests: write

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: |
          nix build
          cp result/codekraft-101_core.pdf output/
      - run: nix flake check
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"
          git add .
          git commit -m "[GitHub Actions] Build Typst File"
          git push


